server:
  port: 8082
spring:
  datasource:
    db01:
      jdbcUrl: jdbc:mysql://localhost:3339/sharding01?useSSL=false&useUnicode=yes&characterEncoding=utf8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    db02:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3340/sharding01?useSSL=false&useUnicode=yes&characterEncoding=utf8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
