server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3339/mybatis?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true   #自动提交
      connection-timeout: 30000 #等待连接池分配连接的最大时长
      minimum-idle: 5   #最小连接数
      maximum-pool-size: 20   #最大连接数
      idle-timeout: 600000   #连接超时的最大时长（毫秒）
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000  #连接的生命时长
      connection-test-query: select 1
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml

